---
title: 光之角落 SunnyCorner B&B
timezone: Asia/Taipei
collections:
  services:
    title: 房間設備
    output: false
  posts:
    title: 文章
    output: true
  uploads:
    title: 檔案
    output: true
  galleries:
    title: 相簿
    output: false
  sections:
    title: 頁面區塊
    output: false
defaults:
- scope:
    path: ''
    type: services
  values:
    icon: solid fa-bed
    name: 床
email: contact@sunnycorner.tw
description: 光之角落只想給大家一個放鬆的地方，來到花蓮就是要逃離都市的快步調，好好享受這花蓮的慢、靜，讓自己放鬆一下。
baseurl: 
url: https://sunnycorner.tw
social:
  facebook: sunnycorner.bb
  facebook_page_id: 100427851380805
  line_link: https://lin.ee/xk7fbT4
google_map_key: AIzaSyB8Y1YIuJ4zq7EBZcXAAqxBEDNDLW326M4
theme: minima
plugins:
- jekyll-sitemap
sass:
  load_paths:
  - _sass
  - _vendor/theme/assets/sass
