---
title: 光之角落 SunnyCorner B&B
timezone: Asia/Taipei
collections:
  galleries:
    title: Galleries
    output: false
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  services:
    title: 房間設備
    output: false
  uploads:
    title: Uploads
    output: true
email: contact@sunnycorner.tw
description: 光之角落只想給大家一個放鬆的地方，來到花蓮就是要逃離都市的快步調，好好享受這花蓮的慢、靜，讓自己放鬆一下。
baseurl:
url: https://sunnycorner.tw
social:
  facebook: sunnycorner.bb
  facebook_page_id: 100427851380805
  line_link: https://lin.ee/xk7fbT4
google_map_key: AIzaSyB8Y1YIuJ4zq7EBZcXAAqxBEDNDLW326M4
theme: minima
plugins:
- jekyll-sitemap
sass:
  load_paths:
  - _sass
  - _vendor/theme/assets/sass
defaults:
  - scope:
      path: ""
      type: "services"
    values:
      icon: solid fa-bed
      name: 床
